# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check Info

on:
  workflow_dispatch:
  repository_dispatch:
    types: check-info
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-check-info-job:
    runs-on: ubuntu-latest
    container:
      image: d4rkk3y/python-auto-env:latest
      env:
        RUN_PY: ${{ secrets.RUN_PY }}
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run check-info task
        run: |
          python run.py $RUN_PY
